from importlib.util import find_spec

optional_hiddenimports = []
if find_spec('crimson_rs') is not None:
    optional_hiddenimports = [
        'crimson_rs',
        'crimson_rs.enums',
        'crimson_rs.create_pack',
        'crimson_rs.pack_mod',
        'crimson_rs.validate_game_dir',
    ]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('parc_parser.dll', '.'),
        ('item_names.json', '.'),
        ('store_names.json', '.'),
        ('item_templates.json', '.'),
        ('master_templates.json', '.'),
        ('item_limits.json', '.'),
        ('item_category_map.json', '.'),
        ('max_enchant_map.json', '.'),
        ('waypoint_templates_community.json', '.'),
        ('abyss_gimmick_templates.json', '.'),
        ('knowledge_keys_all.json', '.'),
        ('community_knowledge_keys.json', '.'),
        ('quest_names.json', '.'),
        ('quest_database.json', '.'),
        ('mission_names.json', '.'),
        ('quest_stage_map.json', '.'),
        ('stage_names.json', '.'),
        ('gimmick_respawn_timers.json', '.'),
        ('quest_chains.json', '.'),
        ('dye_slot_counts.json', '.'),
        ('buff_skill_descriptions.json', '.'),
        ('game_map.json', '.'),
        ('localizationstring_eng_items.tsv', '.'),
        ('editor_version_standalone.json', '.'),
        ('save_schema_profiles.json', '.'),
        ('locale', 'locale'),
        ('knowledge_packs', 'knowledge_packs'),
    ],
    hiddenimports=[
        'lz4',
        'lz4.block',
        'cryptography',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        'iteminfo_parser',
        'parc_inserter3',
        'parc_inserter2',
        'parc_serializer',
        'save_parser',
        'save_pet_rename',
        'quest_deep_parser',
        'questinfo_parser',
        'item_template_db',
        'ben_save_decrypt',
        'app_logging',
        'save_compat',
        'blackstar_unlock',
        'blackstar_worker',
    ] + optional_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt5'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

splash = Splash(
    'splash.png',
    binaries=a.binaries,
    datas=a.datas,
    text_pos=(24, 195),
    text_size=10,
    text_color='#F0F0F5',
    text_default='Initializing...',
    always_on_top=True,
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    splash,
    splash.binaries,
    [],
    name='CrimsonSaveEditorStandalone',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    icon='app_icon.ico',
    codesign_identity=None,
    entitlements_file=None,
)
